config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
  # Defines the root path route ("/")
  root "pages#home"
  get "/clear", to: "pages#clear", as: :clear
  get '/login/:token', to: 'login#show', as: :login
  get '/logout', to: 'login#destroy', as: :logout
  resources :groups, only: [:new, :create, :show] do
    get :user_row, on: :collection
  end
  resources :users, only: [:show] do
    resources :transactions
    post :search, on: :collection
    get :repetitions, on: :member
  end
  resources :repetitions, only: [:create, :new, :edit, :update, :destroy]
  resources :transactions, only: [:show, :index] do
    get :balance, on: :collection
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
  has_many :transactions, through: :users

  accepts_nested_attributes_for :users

  before_create :assign_slug

  def balance
    Money.new(transactions.balance)
  end

  private

  def assign_slug
    self.slug ||= SecureRandom.alphanumeric(10).downcase
  end
end

# == Schema Information
#
# Table name: groups
#
#  id         :bigint           not null, primary key
#  name       :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :user_row]

  def show
    @group = current_user.group
    @shared = shared(default: true)
    @timing = timing
  end

  def new
    @group = Group.new
    @group.users.build(email: params[:email])
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      auto_login(@group.users.first)
      @group.users.drop(1).each{|u| u.deliver_magic_login_instructions!}
      redirect_to group_path(@group.slug)
    else
      render :new
    end
  end

  def user_row
    index = params[:index]&.to_i
    render turbo_stream: [
      turbo_stream.append("users", partial: 'groups/user_row', locals: {index: index} ),
      turbo_stream.update("new-user-button", partial: 'groups/user_button', locals: {index: index + 1} )
    ]
  end

  private

  def group_params
    params.require(:group).permit(:name, users_attributes: [:email, :name])
  end
end

app/views/groups/_form.html.haml
= form_with model: @group do |f|
  .MarginBottom
    .MarginBottom= f.label :name, class: 'Label'
    = f.text_field :name, placeholder: t('.group_name'), required: true, autofocus: true, class: 'Input'
  .Headline.MarginBottom= t('.users')
  %turbo-frame#users
    - @group.users.each_with_index do |user, index|
      = render 'user_row', name: user.name, email: user.email, index: index
  .Flex.asCenter.MarginTop.MarginBottom
    %turbo-frame#new-user-button
      = render 'groups/user_button', index: @group.users.size
    = f.submit t('.submit'), class: 'Button'

app/views/groups/_user_button.html.haml
= link_to t('.add_user'), user_row_groups_path(index: index), class: 'Button asSecondary asSmall', data: { turbo_stream: 'new-users-button' }

app/views/groups/_user_row.html.haml
- user ||= ""
- email ||= ""
.MarginBottom
  .MarginBottom
    .Label
      = t('.name')
      = "(Nr.#{index + 1})"
  = text_field_tag "group[users_attributes][#{index}][name]", user, placeholder: t('.name'), required: true, class: 'Input', data: { controller: (index > 0 ? 'auto-focus' : '') }
.MarginBottom
  .MarginBottom
    .Label= t('.email')
  = email_field_tag "group[users_attributes][#{index}][email]", email, placeholder: t('.email'), required: true, class: 'Input'

app/views/groups/new.html.haml
.MainContent
  .HeaderComponent
    .HeaderComponent-title.MarginBottom= t('.welcome')
    .Box
      .Headline.asDark= t('.new_group')
    .MarginTop
      = render 'form', group: @group

app/views/groups/show.html.haml
= render HeaderComponent.new(source: @group, timing: @timing, shared: @shared)
.Margin.MainContent
  .Headline.MarginBottom
    = @shared ? t('common.shared_transactions') : t('common.all_transactions')
  = render TransactionListComponent.new(source: @group, timing: params[:timing], only_shared: @shared)

.Bottom
  .MainContent
    = turbo_frame_tag :new_transaction do
      = render 'users/new_transaction', user: current_user