config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
  # Defines the root path route ("/")
  root "pages#home"
  get "/clear", to: "pages#clear", as: :clear
  get '/login/:token', to: 'login#show', as: :login
  get '/logout', to: 'login#destroy', as: :logout
  resources :groups, only: [:new, :create, :show] do
    get :user_row, on: :collection
  end
  resources :users, only: [:show] do
    resources :transactions
    post :search, on: :collection
    get :repetitions, on: :member
  end
  resources :repetitions, only: [:create, :new, :edit, :update, :destroy]
  resources :transactions, only: [:show, :index] do
    get :balance, on: :collection
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  belongs_to :group
  has_many :transactions
  has_many :repetitions

  before_create :assign_slug

  validates :email, presence: true, uniqueness: true

  def to_param
    slug
  end

  def initials
    name.first.upcase
  end

  private

  def assign_slug
    self.slug ||= SecureRandom.alphanumeric(10).downcase
  end
end

# == Schema Information
#
# Table name: users
#
#  id                           :bigint           not null, primary key
#  crypted_password             :string
#  email                        :string
#  magic_login_email_sent_at    :datetime
#  magic_login_token            :string
#  magic_login_token_expires_at :datetime
#  name                         :string
#  remember_me_token            :string
#  remember_me_token_expires_at :datetime
#  salt                         :string
#  slug                         :string
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  group_id                     :bigint           not null
#
# Indexes
#
#  index_users_on_group_id           (group_id)
#  index_users_on_magic_login_token  (magic_login_token)
#  index_users_on_remember_me_token  (remember_me_token)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:search]

  def show
    @user = User.find_by!(slug: params[:id].downcase)
    @shared = shared(default: false)
    @timing = timing
  end

  def search
    @user = User.find_by(email: params[:email])
    if @user
      @user.deliver_magic_login_instructions!
      redirect_to root_path, notice: 'Du hast eine E-Mail zum Einloggen erhalten'
    else
      redirect_to new_group_path(email: params[:email])
    end
  end

  def repetitions
    @user = User.find_by!(slug: params[:id].downcase)
    @repetitions = @user.repetitions.active.order(:timing)
  end

  private

  def transactions
    result = @user.transactions
    result = result.shared if @shared
    result.order(date: :desc).send(timing)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new_transaction.html.haml
= link_to new_user_transaction_path(user.slug), class: 'Button asFullWidth' do
  = t('.button')

app/views/users/repetitions.html.haml
.Margin.MainContent
  %table.Table
    %thead
      %tr
        %th= 'Timing'
        %th= 'Status'
        %th= 'Nächste Ausführung'
    %tbody
      - @repetitions.each do |repetition|
        %tr.Table-row
          %td= repetition.timing
          %td= repetition.active ? 'Aktiv' : 'Inaktive'
          %td= l(repetition.next_iteration.to_date)
        - repetition.transactions.order(date: :desc).each do |transaction|
          %tr.Table-row.asSub
            %td= transaction.name
            %td= balance_money_tag transaction.amount
            %td= l(transaction.date)

app/views/users/show.html.haml
= render HeaderComponent.new(source: @user, timing: @timing, shared: @shared)
.Margin.MainContent
  .Headline.MarginBottom
    = @shared ? t('common.shared_transactions') : t('common.all_transactions')
  = render TransactionListComponent.new(source: @user, timing: @timing, only_shared: @shared)

- if @user == current_user
  .Bottom
    .MainContent
      = turbo_frame_tag :new_transaction do
        = render 'new_transaction', user: current_user