config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
  # Defines the root path route ("/")
  root "pages#home"
  get "/clear", to: "pages#clear", as: :clear
  get '/login/:token', to: 'login#show', as: :login
  get '/logout', to: 'login#destroy', as: :logout
  resources :groups, only: [:new, :create, :show] do
    get :user_row, on: :collection
  end
  resources :users, only: [:show] do
    resources :transactions
    post :search, on: :collection
    get :repetitions, on: :member
  end
  resources :repetitions, only: [:create, :new, :edit, :update, :destroy]
  resources :transactions, only: [:show, :index] do
    get :balance, on: :collection
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @user = User.find_by(slug: params[:user_id])
    @transaction = @user.transactions.new(date: Date.today)
  end

  def create
    @user = User.find_by(slug: params[:user_id])
    @transaction = @user.transactions.new(transaction_params)
    if @transaction.save
      render turbo_stream: turbo_stream.update("new_transaction", partial: 'users/new_transaction', locals: { user: current_user })
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(slug: params[:user_id])
    @transaction = @user.transactions.find(params[:id])
    render turbo_stream: update_with_form
  end

  def show
    @user = User.find_by(slug: params[:user_id])
    @transaction = @user.transactions.find(params[:id])
    render turbo_stream: replace_with_show
  end

  def update
    @user = User.find_by(slug: params[:user_id])
    @transaction = @user.transactions.find(params[:id])
    if @transaction.update(transaction_params)
      render turbo_stream: replace_with_show(highlight: true)
    else
      render turbo_stream: update_with_form
    end
  end

  def destroy
    @user = User.find_by(slug: params[:user_id])
    @transaction = @user.transactions.find(params[:id])
    @transaction.destroy
    redirect_to user_path(@user.slug)
  end

  def index
    @transactions = transaction_search_results
    @categories = @transactions.map(&:category).uniq
    render partial: '/transactions/list', locals: {transactions: @transactions}
  end

  def balance
    source = params.dig(:source_type).constantize.find(params.dig(:source_id))
    shared = shared(default: source.is_a?(User))
    interactor = BalanceCalculator.call(source: source, timing: timing, shared: shared)

    render turbo_stream: turbo_stream.update(interactor.identifier, partial: '/transactions/balance', locals: { balance: interactor.balance })
  end

  private

  def replace_with_show(highlight: false)
    turbo_stream.replace(
      "transaction_#{@transaction.id}",
      partial: 'transactions/transaction',
      locals: {transaction: @transaction, highlight: highlight}
    )
  end

  def update_with_form
    url = user_transaction_path(@user.slug, @transaction)
    turbo_stream.update(
      "transaction_#{@transaction.id}",
      partial: 'transactions/form',
      locals: {url: url, transaction: @transaction}
    )
  end

  def transaction_search_results
    if params[:source].blank?
      base = Transaction.all
    else
      @source = params.dig(:source, :type).constantize
      base = @source.find_by(slug: params.dig(:source, :id)).transactions
    end
    @timing = timing
    base = base.send(@timing)
    base = base.shared if shared(default: false)
    @q = base.ransack(params[:q])
    @q.result(distinct: true).order(date: :desc, created_at: :desc)
  end

  def transaction_params
    par = params.require(:transaction).permit(:amount, :name, :category, :date, :shared)
    par[:amount] = par[:amount].to_f * -1 if params[:outgoing]
    par
  end
end

app/views/transactions/_balance.html.haml
= balance_money_tag(balance)

app/views/transactions/_form.html.haml
= form_with model: transaction, url: url, class: 'Form', data: { 'turbo-frame': '_top' } do |f|
  .MarginBottom
    = f.number_field :amount, value: transaction.amount&.abs&.to_f, class: 'Input asMain', placeholder: '0.00', step: 0.01, min: 0.01, data: { controller: 'auto-focus' }, required: true

  %label.InOut
    = check_box_tag :outgoing, true, transaction.outgoing?, class: 'InOut-checkbox'
    .InOut-content
      .InOut-content-check= t('.outgoing')
      .InOut-content-noncheck= t('.incoming')
  .Flex.MarginBottom
    .Flex-item
      .MarginBottomSmall= f.label :category, class: 'Label'
      = f.select :category, options_for_select(category_options, transaction.category), {}, class: 'Select'
    .Flex-item
      .MarginBottomSmall= f.label :date, class: 'Label'
      = f.date_field :date, class: 'Input'
  .MarginBottomSmall= f.label :name, class: 'Label'
  .MarginBottom= f.text_field :name, class: 'Input', autocomplete: 'off'
  .MarginBottom
    %label.CheckboxLabel
      = f.check_box :shared, value: true, class: 'Checkbox'
      = t('.shared')
  .Flex
    - url = transaction.persisted? ? transaction_path(transaction, user_id: transaction.user) : user_path(transaction.user.slug)
    = link_to t('common.cancel'), url, class: 'Link'
    = f.submit t('common.submit'), class: 'Button'
    - if transaction.persisted?
      = link_to t('common.delete'), user_transaction_path(transaction.user.slug, transaction), data: { turbo_confirm: t('common.confirm'), turbo_method: :delete }, class: 'Link'

app/views/transactions/_list.html.haml
%turbo-frame#transactions
  = search_form_for @q, url: url_for, data: { controller: 'auto-submit', turbo_frame: "transactions-results-#{@shared}"} do |f|
    = hidden_field_tag :shared, @shared
    = hidden_field_tag :timing, @timing
    = hidden_field_tag 'source[id]', params.dig(:source, :id)
    = hidden_field_tag 'source[type]', params.dig(:source, :type)
    .MarginBottom
      .Flex
        = f.search_field :name_cont, data: { action: 'keyup->auto-submit#submit' }, autocomplete: "off", class: 'Input', placeholder: t('common.search')
        = f.select :category_eq, options_for_select(category_options(@categories), params[:category_eq]), { prompt: 'Alle Kategorien' }, {data: { action: 'change->auto-submit#submit' }, class: 'Select'}
    = f.submit "Search", class: 'Hidden'
  %turbo-frame{id: "transactions-results-#{@shared}"}
    - if @source == Group
      .MarginBottom= render CategoriesComponent.new(transactions: transactions)
    - transactions.each do |transaction|
      = render 'wrapper', transaction: transaction

app/views/transactions/_transaction.html.haml
- highlight ||= false
%turbo-frame{ id: dom_id(transaction) }
  = render TransactionComponent.new(transaction: transaction, highlight: highlight)

app/views/transactions/_wrapper.html.haml
- highlight ||= false
%turbo-frame{ id: "wrapper_transaction_#{transaction.id}" }
  .MarginBottomSmall
    = render 'transactions/transaction', transaction: transaction, highlight: highlight

    %turbo-frame{ id: "repetition_transaction_#{transaction.id}" }

app/views/transactions/new.html.haml
= turbo_frame_tag :new_transaction do
  = render 'form', url: user_transactions_path(@user.slug), transaction: @transaction